import {
    Button,
    VerticalBox,
    GroupBox,
    CheckBox,
    ListView,
    HorizontalBox,
    LineEdit,
} from "std-widgets.slint";
import "../font/NotoSansSC-Regular.ttf";

export component AppWindow inherits Window {
    default-font-family: "Noto Sans SC";
    title: "File Cleaner";
    width: 800px;
    height: 600px;

    in-out property <string> selected_directory;
    in-out property <bool> org_enabled;
    in-out property <bool> html_enabled;
    in-out property <bool> dsstore_enabled;
    in-out property <string> action_text;
    in-out property <[string]> scan_results;

    callback choose_dir();
    callback action_clicked();

    in-out property <[string]> current_path_parts;
    in-out property <[string]> folder_list;
    callback path_part_clicked(int);
    callback folder_clicked(string);

    // Directory Select Area
    VerticalBox {
        spacing: 20px;
        padding: 20px;
        GroupBox {
            title: "Choose Dir";
            VerticalBox {
                spacing: 10px;
                padding: 6px;
                HorizontalBox {
                    spacing: 4px;
                    for path_part[i] in current_path_parts: Button {
                        text: path_part;
                        clicked => {
                            path_part_clicked(i);
                        }
                    }
                }
            }

            ListView {
                for item in folder_list: Button {
                    text: item;
                    clicked => {
                        root.folder_clicked(item);
                    }
                }
            }
        }

        // Scan Results
        GroupBox {
            title: "Scan Results";
            VerticalBox {
                spacing: 8px;
                padding: 6px;
                ListView {
                    for item in scan_results: Rectangle {
                        height: 22px;
                        background: #f7f7f7;
                        border-radius: 4px;
                        Text {
                            text: item;
                            font-size: 13px;
                            vertical-alignment: center;
                        }
                    }
                }
            }
        }

        // Target File Types
        GroupBox {
            title: "Target File Type: ";

            VerticalBox {
                spacing: 10px;
                padding: 6px;

                CheckBox {
                    text: "*.org~";
                    checked: org_enabled;
                    toggled => {
                        root.action_text = "Scan"
                    }
                }

                CheckBox {
                    text: "*.html~";
                    checked: org_enabled;
                    toggled => {
                        root.action_text = "Scan"
                    }
                }

                CheckBox {
                    text: ".DS_Store";
                    checked: org_enabled;
                    toggled => {
                        root.action_text = "Scan"
                    }
                }
            }
        }

        // Action Button
        Button {
            text: action_text;
            height: 48px;
            horizontal-stretch: 1;
            clicked => {
                root.action_clicked()
            }
        }
    }
}
